In [3]:
print("hello")

hello


In [4]:
import numpy as np 
a=np.array([1,2,3])
b=a
c=np.copy(a)
print(a is b)
print(a is c)

True
False


In [5]:
import numpy as np 
a = np.array ([1,2,3])
b=a

In [6]:
import numpy as np 
a = np.array([[1,2],[3,4]])
b=a.copy()
print(a is b)

False


In [7]:
import numpy as np 
a =np.array([10,20,30,40])
b=a.view()
c=a.copy()
print(a is b)
print(a is c)
print(b.base is a)
print(c.base)

False
False
True
None


In [8]:
import numpy as np

zeros = np.zeros((3, 4))
ones = np.ones((3, 4))
eye = np.eye(4)

arrays = {
    "Zeros": zeros,
    "Ones": ones,
    "Eye": eye
}

for name, arr in arrays.items():
    print(name)
    print("Shape :", arr.shape)
    print("Size  :", arr.size)
    print("Ndim  :", arr.ndim)
    print("Dtype :", arr.dtype)
    print()

print("Eye matrix row by row:")
for row in eye:
    for value in row:
        print(int(value), end=" ")
    print()

eye_copy = eye.copy()

print("\nIndependent copy?")
print(eye is eye_copy)

Zeros
Shape : (3, 4)
Size  : 12
Ndim  : 2
Dtype : float64

Ones
Shape : (3, 4)
Size  : 12
Ndim  : 2
Dtype : float64

Eye
Shape : (4, 4)
Size  : 16
Ndim  : 2
Dtype : float64

Eye matrix row by row:
1 0 0 0 
0 1 0 0 
0 0 1 0 
0 0 0 1 

Independent copy?
False


In [9]:
import numpy as np

zeros = np.zeros((3, 4))
ones = np.ones((3, 4))
eye = np.eye(4)

print("Zeros")
print(zeros)
print("Shape:", zeros.shape)
print("Size:", zeros.size)
print("Ndim:", zeros.ndim)
print("Dtype:", zeros.dtype)

print("\nOnes")
print(ones)
print("Shape:", ones.shape)
print("Size:", ones.size)
print("Ndim:", ones.ndim)
print("Dtype:", ones.dtype)

print("\nEye")
print(eye)
print("Shape:", eye.shape)
print("Size:", eye.size)
print("Ndim:", eye.ndim)
print("Dtype:", eye.dtype)

print("\nEye matrix row by row")
for i in range(4):
    for j in range(4):
        print(int(eye[i][j]), end=" ")
    print()

copy_eye = eye.copy()

print("\nIs it an independent copy?")
print(copy_eye is eye)

Zeros
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (3, 4)
Size: 12
Ndim: 2
Dtype: float64

Ones
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Shape: (3, 4)
Size: 12
Ndim: 2
Dtype: float64

Eye
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Shape: (4, 4)
Size: 16
Ndim: 2
Dtype: float64

Eye matrix row by row
1 0 0 0 
0 1 0 0 
0 0 1 0 
0 0 0 1 

Is it an independent copy?
False


In [10]:
import numpy as np

one_d = np.array([10, 20, 30, 40, 50])

two_d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

three_d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("1D Array")
print(one_d)
print("Shape:", one_d.shape)
print("Size:", one_d.size)
print("Ndim:", one_d.ndim)
print("Dtype:", one_d.dtype)

print("\n2D Array")
print(two_d)
print("Shape:", two_d.shape)
print("Size:", two_d.size)
print("Ndim:", two_d.ndim)
print("Dtype:", two_d.dtype)

print("\n3D Array")
print(three_d)
print("Shape:", three_d.shape)
print("Size:", three_d.size)
print("Ndim:", three_d.ndim)
print("Dtype:", three_d.dtype)

1D Array
[10 20 30 40 50]
Shape: (5,)
Size: 5
Ndim: 1
Dtype: int64

2D Array
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Ndim: 2
Dtype: int64

3D Array
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
Size: 8
Ndim: 3
Dtype: int64


In [11]:
import numpy as np

a = np.array([
    [
        [[1, 2], [3, 4]],
        [[5, 6], [7, 8]]
    ],
    [
        [[9, 10], [11, 12]],
        [[13, 14], [15, 16]]
    ]
])

print(a)
print("shape:", a.shape)
print("size:", a.size)
print("ndim:", a.ndim)
print("dtype:", a.dtype)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
shape: (2, 2, 2, 2)
size: 16
ndim: 4
dtype: int64
