In [1]:
print ("hello")

hello


In [ ]:
#split into equal parts
import numpy as np 
a=np.array([1,2,3,4,5,6])
print(np.split(a,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [10]:
import numpy as np 
a=np.array([[1,2],
           [3,4],
           [5,6],
           [7,8]] )
print(np.split(a,2))

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [12]:
#split column wise 
import numpy as np 
a=np.array([[1,2,3,4],
           [5,6,7,8]])
print(np.hsplit(a,2))

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [13]:
import numpy as np 
a=np.array([5,10,15,20,25])
print(a)
print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype)

[ 5 10 15 20 25]
(5,)
5
1
int64


In [15]:
import numpy as np 
a=np.array([[1,2,3,4],
            [5,6,7,8]
])
print(a)
print(a.size)
print(a.shape)
print(a.ndim)

[[1 2 3 4]
 [5 6 7 8]]
8
(2, 4)
2


In [16]:
import numpy as np

a = np.arange(1, 9).reshape(2, 4)

print(a)
print(a.shape)
print(a.size)
print(a.ndim)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
8
2


In [17]:
import numpy as np

a = np.array([[2, 4, 6], [8, 10, 12]])

print(a.shape)
print(a.size)
print(a.ndim)

(2, 3)
6
2


In [20]:
import numpy as np 
a=np.zeros(7)
print(a)
print(a.dtype)

[0. 0. 0. 0. 0. 0. 0.]
float64


In [22]:
import numpy as np 
a=np.zeros((3,4))
print(a)
print(a.shape)
print(a.size)
print(a.ndim)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)
12
2


In [23]:
import numpy as np 
a=np.ones(6)
print(a)
print(a.shape)

[1. 1. 1. 1. 1. 1.]
(6,)


In [26]:
import numpy as np
a=np.ones((2,5))
print(a) 
print(a.size)
print(a.ndim)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
10
2


In [29]:
import numpy as np 
a=np.eye(4)
print(a)
print(a.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)


In [30]:
import numpy as np 
a=np.eye(3,5)
print(a)
print(a.size)
print(a.ndim)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
15
2


In [31]:
import numpy as np 
a=np.eye(3,5)
print(a)
print(a.size)
print(a.ndim)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
15
2


In [32]:
import numpy as np

# Integer array (2x3)
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a.dtype)

# Decimal array (2x3)
b = np.array([[1.1, 2.2, 3.3],
              [4.4, 5.5, 6.6]])

print(b.dtype)

int64
float64


In [ ]:
#split using index position
import numpy as np 
a=np.array([1,2,3,4,5,6])
print(np.split(a,[2,5]))

[array([1, 2]), array([3, 4, 5]), array([6])]
