In [1]:
print("helooo")

helooo


In [2]:
import numpy as np
a=np.arange(5) 
print(a)

[0 1 2 3 4]


In [5]:
b=np.arange(2,8)
print(b)

[2 3 4 5 6 7]


In [11]:
import numpy as np 
a=np.array([1,2,3,4,5])
print(a)
print(a.shape)
print(a.ndim)

[1 2 3 4 5]
(5,)
1


In [14]:
import numpy as np 
c=np.arange(10,21,2)
print(c)

[10 12 14 16 18 20]


In [16]:
a=np.arange(1,2,0.2)
print(a)

[1.  1.2 1.4 1.6 1.8]


In [29]:
a=np.array([1,2,3,4,3,2,4,1,4,5])
result={}
for i in a:
    if i not in result:
        result[int(i)]=1
    else:
        result[int(i)]+=1
print(result)           


{1: 2, 2: 2, 3: 2, 4: 3, 5: 1}


In [30]:
import numpy as np
a=np.array([1,2,3,4])
b=a.view()
b[0]=100
print(a)
print(b)

[100   2   3   4]
[100   2   3   4]


In [32]:
import numpy as np 
a=np.array([1,2,3,4])
b=a.copy()
b[0]=100
print(a)
print(b)

[1 2 3 4]
[100   2   3   4]


In [33]:
import numpy as np 
a=np.array([1,2,3,4,5,6])
b=a.reshape(2,3)
print(b)

[[1 2 3]
 [4 5 6]]


In [34]:
b=a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [35]:
# minus one
import numpy as np 
a=np.array([1,2,3,4,5,6])
b=a.reshape(2,-1)
print(b)

[[1 2 3]
 [4 5 6]]


In [38]:
import numpy as np 
a=np.array([1,2,3,4,5])
b=a.reshape(-1,1)
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [39]:
import numpy as np 
a=np.array([1,2,3,4,5])
b=a.reshape(1,-1)
print(b)

[[1 2 3 4 5]]


In [ ]:
# 1d
import numpy as np 
a=np.array([1,2,3,4])
b=np.array([5])
c=np.concatenate((a,b))
print(c)

[1 2 3 4 5]


In [43]:
#2d
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.concatenate((a,b),axis=0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [44]:

print(np.concatenate((a,b), axis=1))

[[1 2 5 6]
 [3 4 7 8]]
