In [1]:
print("hello")

hello


In [2]:
import numpy as np 
a =np.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [4]:
import numpy as np 
a= np.zeros(5)
print(a)
print(a.shape)
print(a.size)
print(a.ndim)

[0. 0. 0. 0. 0.]
(5,)
5
1


In [5]:
import numpy as np 
a= np.array([5,10,15,20,25])
print(a)
print(a.dtype)

[ 5 10 15 20 25]
int64


In [8]:
import numpy as np 
a =np.ones([3,3])
print(a)
print(a.shape)
print(a.ndim)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(3, 3)
2


In [9]:
import numpy as np 
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
import numpy as np 
a= np.array([12,7,19,4,25])
print(a[0])
print(a[-1])
print(a[2])

12
25
19


In [13]:
import numpy as np 
a = np.arange(2,21,2)
print(a)
print(len(a))
print(a.size)

[ 2  4  6  8 10 12 14 16 18 20]
10
10


In [14]:
import numpy as np 
arr = np.arange(1,13).reshape(3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
import numpy as np 
arr=np.array([[1,2,3],
[4,5,6]])
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

(2, 3)
6
2
int64


In [16]:
import numpy as np 
a=np.array([3,6,9,12,15])
for i in a:
    print(i)

3
6
9
12
15


In [20]:
import numpy as np 
a=np.arange(1,10).reshape(3,3)
for i in  a:
    for j in i:
     print(j,end=" ")


1 2 3 4 5 6 7 8 9 

In [22]:
import numpy as np 
a=np.arange(1,10).reshape(3,3)
for i in  a:
    for j in i:
     print(j,end=" ")
    print()


1 2 3 
4 5 6 
7 8 9 


In [26]:
import numpy as np 
a = np.array([1.6,2.7,3.1,4.2])
print(a.dtype)
new_arr=a.astype(int)
print(new_arr)

float64
[1 2 3 4]


In [28]:
#13
import numpy as np
a=np.array([10,20,30,40,50,60])
print(a.shape)
new=a.reshape(2,3)
print(new)
print(new.shape)

(6,)
[[10 20 30]
 [40 50 60]]
(2, 3)


In [31]:
import numpy as np 
a=np.arange(1,13).reshape(3,4)
print(a.shape)
print(a.size)
print(a.ndim)

(3, 4)
12
2


In [34]:
import numpy as np 
a=np.array([1,2,3,4])
b=np.array([10,20,30,40])
print(a+b)
print(b-a)
print(a*b)
print(b/a)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


In [39]:
import numpy as np 
a=np.array([72,85,91,64,78])
sum=0
for i in a:
    sum+=i
print(sum) 
print(sum/len(a))   

390
78.0


In [40]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

copy_arr = arr.copy()
same_arr = arr

# copy() creates an independent copy
# same_arr is another reference to the same array

print(copy_arr is arr)
print(same_arr is arr)

False
True


In [1]:
import numpy as np 
a =np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
b=a.view() 
print(a is b)            


False


In [2]:
import numpy as np

arr = np.array([11, 22, 33, 44, 55])

print("dtype:", arr.dtype)
print("ndim:", arr.ndim)
print("size:", arr.size)
print("shape:", arr.shape)

dtype: int64
ndim: 1
size: 5
shape: (5,)


In [4]:
import numpy as np

arr = np.arange(1, 21).reshape(4, 5)

print(arr)
print("shape:", arr.shape)
print("size:", arr.size)
print("ndim:", arr.ndim)
print("dtype:", arr.dtype)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
shape: (4, 5)
size: 20
ndim: 2
dtype: int64


In [37]:
import numpy as np

marks = np.array([72, 85, 91, 64, 78])

total = np.sum(marks)
average = np.mean(marks)

print(total)
print(average)

390
78.0
