In [1]:
print("hello")

hello


In [2]:
import numpy as np 
a=np.zeros((3,2,4))
print(a)
print(a.shape)
print(a.size)
print(a.ndim)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
(3, 2, 4)
24
3


In [3]:
import numpy as np 
a=np.ones((2,3,4))
print(a)
print(a.shape)
print(a.size)
print(a.ndim)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
(2, 3, 4)
24
3


In [8]:
import numpy as np 
a=np.eye(5)
print(a)
for row in a:
    print(row)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 0. 1. 0. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 0. 0. 1.]


In [9]:
import numpy as np 
a=np.array([[10,20,30],[40,50,60]])
for i in range(len(a)):
    for j in range(len(a[i])):
        print(a[i][j])

10
20
30
40
50
60


In [11]:
import numpy as np 
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
for i in range(len(a)):
    for j in range (len(a[i])):
        print(a[i][j])


1
2
3
4
5
6
7
8
9


In [ ]:
import numpy as np
a = np.array([[1,2,3,4],
              [5,6,7,8]])
for i in range(len(a)):
    for j in range(len(a[i])):
        print(a[i][j], end=" ")
    print()

1 2 3 4 
5 6 7 8 


In [15]:
import numpy as np 
a=np.ones([8])
print(a)
for i in a:
    print(i)
print(a.size)    

[1. 1. 1. 1. 1. 1. 1. 1.]
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
8


In [18]:
import numpy as np 
a=np.array([10,20,30,40])
print(a)
for i in range(len(a)):
    print("index:",i,"value:",a[i])

[10 20 30 40]
index: 0 value: 10
index: 1 value: 20
index: 2 value: 30
index: 3 value: 40


In [22]:
import numpy as np
a=np.array([[1,2,3],
            [4,5,6]])
sum=0
for i in a:
    for j in i:
      sum=sum+j
print(sum)    


21


In [23]:
import numpy as np
a=np.array([[1,2,3],
            [4,5,6]])
sum=0
for i in a:
      sum=sum+i
print(sum)    


[5 7 9]


In [26]:
import numpy as np
a=np.array([[1,2,3],
            [4,5,6]])
count=0
for i in a:
    for j in i:
      count+=1
print(count)    


6
